# Header

menu:
  主页: https://justonce.netlify.app/
  随笔: /
  归档:  /archives
  分类:  /categories


# SubNav
subnav:
  twitter: https://twitter.com/Daishunbo
  weibo: https://m.weibo.cn/profile/2552867547
  zhihu: https://www.zhihu.com/people/dai-shun-bo-78
  bilibili: https://space.bilibili.com/98536865/favlist
  github: https://github.com/Just-once
  qq: https://cdn.jsdelivr.net/gh/Just-once/BlogImages/Img/QQ.jpg
  weixin: https://cdn.jsdelivr.net/gh/Just-once/BlogImages/Img/%E5%BE%AE%E4%BF%A1.jpg
  mail: mailto:1191402895@qq.com

  #rss: "#"
  #qq: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #linkedin: "#"
  #rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字 more
excerpt_link: 
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechatpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的……'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: true

#2、网易云跟帖
wangyiyun:  true

#3、畅言
changyan_appid: true
changyan_conf: true

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: true

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'
  

friends:
  Huang's Matrix: https://huangzhw0221.github.io
  Bruce Yao: https://zfyao666.github.io
  #友情链接3: http://localhost:4000/

aboutme: 研究生在读<br><br>即将沦为程序猿社畜<br><br>喜欢音乐、阅读、运动、烹饪<br><br>热爱编程、滑雪、旅游<br><br>日常打卡魔都小众美食，探秘魔都迷人旮旯<br><br>一个单纯耿直的大男孩<br><br>谢谢大家的关注

#文章结束
essayending_type: 2  #0关闭文章结束提示 2全开 1需要在文章开头加上 
essayending: true

#版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
#当前应用的版权协议地址。
#版权协议的名称
#版权协议的Logo
declare_type: 2

# 添加APlayer音乐播放器，官网：https://aplayer.js.org
# github: https://github.com/MoePlayer/APlayer
aplayer:
  enable: true

#头像是否旋转(如果不要旋转取false)
avatarrotation: true

# 鼠标点击显示文字
click_show_text: true